-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Company"
(
    "Company_ID" integer NOT NULL,
    "Company_Name" character varying NOT NULL,
    PRIMARY KEY ("Company_ID")
);

CREATE TABLE IF NOT EXISTS public."Brand"
(
    "Brand_ID" integer NOT NULL,
    "Brand_Name" character varying NOT NULL,
    PRIMARY KEY ("Brand_ID")
);

CREATE TABLE IF NOT EXISTS public."Primary_Category"
(
    "Category_ID" integer NOT NULL,
    "Category_Name" character varying NOT NULL,
    "Description" text,
    PRIMARY KEY ("Category_ID")
);

CREATE TABLE IF NOT EXISTS public."Sub_Category"
(
    "Category_ID" integer NOT NULL,
    "Category_Name" character varying NOT NULL,
    "Description" text,
    PRIMARY KEY ("Category_ID")
);

CREATE TABLE IF NOT EXISTS public."Product"
(
    "Product_ID" integer NOT NULL,
    "Product_Name" character varying NOT NULL,
    "Company_ID" integer NOT NULL,
    "Brand_ID" integer NOT NULL,
    "Primary_Category_ID" integer NOT NULL,
    "Sub_Category_ID" integer NOT NULL,
    PRIMARY KEY ("Product_ID")
);

CREATE TABLE IF NOT EXISTS public."Chemical"
(
    "Chemical_ID" integer NOT NULL,
    "Chemical_Name" character varying NOT NULL,
    PRIMARY KEY ("Chemical_ID")
);

CREATE TABLE IF NOT EXISTS public."Chemical_List"
(
    "Product_ID" integer NOT NULL,
    "Chemical_ID" integer NOT NULL,
    PRIMARY KEY ("Product_ID", "Chemical_ID")
);

ALTER TABLE IF EXISTS public."Product"
    ADD FOREIGN KEY ("Company_ID")
    REFERENCES public."Company" ("Company_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Product"
    ADD FOREIGN KEY ("Brand_ID")
    REFERENCES public."Brand" ("Brand_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Product"
    ADD FOREIGN KEY ("Primary_Category_ID")
    REFERENCES public."Primary_Category" ("Category_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Product"
    ADD FOREIGN KEY ("Sub_Category_ID")
    REFERENCES public."Sub_Category" ("Category_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Chemical_List"
    ADD FOREIGN KEY ("Product_ID")
    REFERENCES public."Product" ("Product_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Chemical_List"
    ADD FOREIGN KEY ("Chemical_ID")
    REFERENCES public."Chemical" ("Chemical_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;