------------------------
--Sub Category Inserts--
------------------------
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('53', 'Lip Color - Lipsticks, Liners, and Pencils');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('25', 'Hair Shampoos (making a cosmetic claim) ');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('46', 'Eyeliner/Eyebrow Pencils');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('52', 'Lip Gloss/Shine');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('48', 'Eye Shadow');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('60', 'Artificial Nails and Related Products');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('162', 'Mascara/Eyelash Products');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('170', 'Hand Cleansers and Sanitizers');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('107', 'Sunscreen (making a cosmetic claim) ');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('168', 'UV Gel Nail Polish');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('61', 'Basecoats and Undercoats');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('166', 'Scrubs and Exfoliants');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('50', 'Foundations and Bases');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('65', 'Nail Polish and Enamel');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('92', 'Anti-Wrinkle/Anti-Aging Products (making a cosmetic claim)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('102', 'Skin Moisturizers (making a cosmetic claim)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('91', 'Acne Products (making a cosmetic claim)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('95', 'Facial Masks');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('51', 'Lip Balm (making a cosmetic claim)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('99', 'Skin Astringent (making a cosmetic claim)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('100', 'Skin Bleaching (making a cosmetic claim) ');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('165', 'Perfumes - Solids and Powders');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('45', 'Blushes ');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('9', 'Bubble and Foam Bath Products');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('93', 'Skin Cleansers');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('159', 'Body Washes and Soaps');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('56', 'Rouges');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('49', 'Face Powders');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('103', 'Skin Toner (making a cosmetic claim)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('157', 'Tattoos and Permanent Makeup');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('98', 'Powders (excluding aftershave, baby powder, and makeup face powder)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('26', 'Hair Styling Products');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('67', 'Other Nail Products ');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('97', 'Nighttime Skin Care');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('109', 'Indoor Tanning Products');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('58', 'Other Makeup Product');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('35', 'Hair Dyes and Colors');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('69', 'Teeth Cleaning Products');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('66', 'Nail Polish and Enamel Removers');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('57', 'Makeup Fixatives');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('164', 'Perfumes - Oils and Lotions');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('21', 'Hair Conditioners (rinse-out)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('105', 'Other Skin Care Product');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('86', 'Shaving Cream and other Beard Softeners');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('62', 'Cuticle Softeners');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('63', 'Nail Creams and Lotions');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('101', 'Skin Fresheners');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('13', 'Cologne');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('77', 'Douches');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('7', 'Bath Additives');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('36', 'Hair Tints and Rinses (coloring)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('71', 'Mouthwashes and Breath Fresheners');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('3', 'Baby Shampoos');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('161', 'Facial Cream');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('42', 'Hair Bleaches');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('34', 'Hair Conditioners (rinse-out)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('20', 'Hair Conditioners (leave-in)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('27', 'Hair Straighteners');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('81', 'Other Personal Care Product ');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('28', 'Permanent Waves and Wave Sets');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('31', 'Other Hair Care Product');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('96', 'Foot Powders and Sprays');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('94', 'Depilatories');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('55', 'Paints (e.g. facial, body)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('41', 'Hair Lighteners with Color');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('83', 'Aftershave Products');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('78', 'Feminine Deodorants');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('104', 'Sprays (excluding fragrances)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('158', 'Baby Wash/Soap');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('108', 'Suntan Enhancers');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('80', 'Underarm Deodorants');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('14', 'Perfumes/Eaux de Parfum');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('4', 'Baby Skin Care');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('16', 'Toilet Water/Eaux de Toilette');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('11', 'Other Bath Products');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('169', 'Hair Shampoos with Anti-Dandruff properties');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('17', 'Other Fragrances');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('38', 'Hair Shampoos (making a cosmetic claim) ');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('33', 'Hair Conditioners (leave-in)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('160', 'Diaper Rash Treatment');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('167', 'Teeth Whitening Products');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('5', 'Other Baby Products');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('39', 'Hair Color Sprays (aerosol)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('172', 'Makeup Preparations');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('75', 'Antiperspirants (making a cosmetic claim)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('89', 'Other Shaving Product');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('163', 'Nail Decoration');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('171', 'Products Related to Hair Coloring');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('79', 'Lubricants  (e.g. personal, sexual, massage oil)');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('72', 'Other Oral Hygiene Product');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('43', 'Other Hair Coloring Product');
INSERT INTO "Sub_Category" ("Category_ID", "Category_Name") VALUES ('110', 'Other Sun-Related Product');

------------------------
--Product Inserts-------
------------------------
