name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "shq2vs7fmc8dbbue6do1wuse"
  title = "Schemas"
  description = "We need a handful of schema objects that can be played with / called."
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "vrcik4selb0uhw3fnpwwf5lf"
  title = "Data Entry"
  description = """
We need to start writing some sql files for inserting.
Start inserting entities that have NO foreign keys in them."""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "izd38qgt9aesss5ejez5x0fa"
  title = "ERD JSON"
  description = "<p>Setting up an erd on the json<br><br>-Connor</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "spn5l2tbm1oimolyqpmpepuj"
  title = "Research Topic"
  description = "We need to find out what we're going to base our database around."
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
