INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('4', 'New Avon LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('338', 'J. Strickland & Co.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('11', 'OPI PRODUCTS INC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('181', 'GOJO Industries, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('27', 'CHANEL, INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('31', 'Aloecare International, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('33', 'Entity Beauty, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('23', 'Revlon Consumer Product Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('43', 'Dermalogica');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('22', 'CLARINS S.A.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('46', 'McConnell Labs, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('841', 'Philosophy');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('55', 'Physician''s Care Alliance, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('67', 'L''Oreal USA');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('69', 'Elizabeth Arden, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('71', 'Sunrider Manufacturing, L.P.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('72', 'Romane Fragrances');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('76', 'LI Pigments');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('70', 'Tahitian Noni International, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('82', 'AMCO International');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('77', 'Buth-na-Bodhaige, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('86', 'The Procter & Gamble Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('84', 'Bare Escentuals Beauty, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('89', 'Regis Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('18', 'Bliss World LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('91', 'Merle Norman Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('96', 'Zotos International, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1093', 'Arcadia Beauty Labs LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('21', 'TIGI Linea Corp');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('101', 'Colomer U.S.A., Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('110', 'Alfalfa Nail Supply, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('116', 'Regis Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('119', 'No Lift Nails Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('125', 'NeoStrata Company, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('128', 'BeautiControl, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('138', 'Klein-Becker USA, LLC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('141', 'Astara Skin Care');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('142', 'Voss Laboratories');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('144', 'C.F.E.B. SISLEY');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('97', 'Whiter Image');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('145', 'Bremenn Research Labs');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('129', 'NOEVIR CO., LTD');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('59', 'Young Nails, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('149', 'Beiersdorf, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('118', 'Added Extras LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('150', 'Giovanni Cosmetics, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('148', 'BEAUTE PRESTIGE INTERNATIONAL');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('159', 'The Procter & Gamble Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('121', 'Cool Cuts 4 Kids');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('120', 'Farouk Systems, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('99', 'BR SAS');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('160', 'Signatry, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('60', 'Chattem, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('167', 'Excelon');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('153', 'Georgia-Pacific Consumer Products LP');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('171', 'Coty');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('172', 'Combe Incorporated');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('30', 'NYX Los Angeles, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('259', 'Primorance');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('111', 'Mazunte LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('164', 'Palladio Beauty Group');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('178', 'Namaste Laboratories');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('95', 'S.C. Johnson & Son, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('417', 'IBS BEAUTY INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1232', 'LEVLAD LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('186', 'Hillyard Industries');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('188', 'Aloette Cosmetics Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('157', 'Added Extras LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('191', 'Benefit Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('177', 'Kiss Products, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('199', 'Tressa Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('954', 'Johnson & Johnson Consumer Companies');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('196', 'Origins Natural Resources Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('176', 'theBalm');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('204', 'Alberto Culver USA, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('197', 'CLINIQUE LABORATORIES, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('195', 'Estee Lauder Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('206', 'Melaleuca, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('202', 'Pure & Basic Products');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('209', 'AFFLINK');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('174', 'John Paul Mitchell Systems');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('211', 'Edward Don & Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('213', 'LagasseSweet');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('973', 'Henkel Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('218', 'Kimberly-Clark Global Sales, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1036', 'The Procter & Gamble Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('222', 'Unite Eurotherapy');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('224', 'Tarte Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('184', 'Conopco, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('216', 'Mannatech Incorporated');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('226', 'purminerals');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('228', 'CosMedix');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('746', 'MULTALER & CIE S.A.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('231', 'Tupperware U.S., Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('221', 'PRESCRIPTIVES INC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('233', 'San Joaquin Supply');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('236', 'BeautyBank Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('235', 'Sun Pharmaceuticals, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('237', 'DARPHIN LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('192', 'Physicians Formula Holdings, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('189', 'Kao USA Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('190', 'Athena Cosmetics, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('239', 'SUPRE');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('242', 'Key Brands International Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('241', 'PBIGROUP INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('24', 'Markwins International, Markwins Beauty Products, Physicians Formula');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('165', 'Regis Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('244', 'LABORATOIRES M&L SA (L''Occitane - Melvita)');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('245', 'COLGATE-PALMOLIVE COMPANY');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('249', 'Molton Brown Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('251', 'PSS World Medical, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('977', 'Pacific World Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('219', 'Perron Rigot');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('254', 'Kevin Murphy');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('256', 'Earth Essentials');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('258', 'Aramis Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('173', 'DHC USA Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('263', 'Sexy Hair');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('264', 'Jurlique International Pty. Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('200', 'LABORATOIRE NUXE');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('265', 'Davines S.p.A.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('229', 'Kao Germany GmbH');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('268', 'PARFUMS GIVENCHY S.A.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('267', 'Kanebo Cosmetics Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('127', 'Shiseido America, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('266', 'Harmon Stores Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('276', 'Access Business Group International, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('270', 'Jo Malone Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('271', 'Ojon Corporationa');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('280', 'Triple S');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('282', 'Corporate Express');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('275', 'Diversey, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('261', 'Beautopia LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('201', 'Hallmark Cards, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('284', 'Murad Skin Research Laboratories, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('287', 'Sonya Dakar Skin Care');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1333', 'SkinMedica, an Allergan Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('288', 'Armand Dupree Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('294', 'Orlane, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('298', 'GUERLAIN');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('753', 'Marianna Industries');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('272', 'Le Groupe Fruits & Passion Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('198', 'S+');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('292', 'Mary Kay Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('304', 'Expanscience Laboratoires');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('303', 'Deb USA, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('285', 'Great Clips, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('262', 'PureTek Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('305', 'Burt''s Bees Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('297', 'Ivy Enterprises, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('313', 'SRC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('310', 'KMC EXIM CORPORATION/DASHING DIVA FRANCHISE CORP');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('312', 'I.C.O.N. Line, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('315', 'General Motors');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('317', 'Nutrimetics Australia Pty Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('301', 'Yves Rocher Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('246', 'Bonne Bell, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('327', 'Nail Magic LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('328', 'Parfums Christian Dior');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('248', 'NSE Products, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('44', 'Thierry Mugler Parfums');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('291', 'Stila Styles LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('175', 'Neways');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('333', 'Bioelements, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('158', 'Anastasia Beverly Hills, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('340', 'Energizer Personal Care, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('277', 'Coria Laboritories');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('342', 'CALIFORNIA NORTH');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('343', 'Penhaligon''s Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('345', 'MAKE UP FOREVER');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('20', 'Obagi Medical Products, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('347', 'Xtreme Color, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('350', 'ANC SPA INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('335', 'CARITA INTERNATIONAL');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('334', 'Laboratoires DECLEOR');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('355', 'LES SALONS DU PALAIS ROYAL SHISEIDO');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('357', 'Crabtree & Evelyn, Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('356', 'Fashion Fair, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('362', 'STENDHAL');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('365', 'ZO Skin Health, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('361', 'Kingdom Animalia, LLC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('367', 'Australian Gold');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('321', 'BEAUTY SOCIETY, INC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('353', 'KORRES S.A - NATURAL PRODUCTS');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('351', 'Shiseido Co., Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('435', 'Bath & Body Works');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('308', 'JAFRA COSMETICS INTERNATIONAL');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('352', 'Nars Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('370', 'Tammy Taylor Nails, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('372', 'American International Industries');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('290', 'Arbonne International LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('373', 'LVMH FRAGRANCE BRANDS');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('374', 'Beauty Selectives');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('377', 'GURWITCH PRODUCTS');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('369', 'KINGS AND QUEENS LTD');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('382', 'ProClean Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('384', 'The Home Depot');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('380', 'US CosmeceuTechs, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('376', 'LVMH FRAGRANCE BRANDS - KENZO PARFUMS');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('269', 'Max Huber Research Labs, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('386', 'Pro-Link Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('388', 'Prime Source LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('390', 'W. W. Grainger, Inc.,');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('393', 'WAXIE Sanitary Supply');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('240', 'GAP INC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('396', 'ORLY INTERNATIONAL');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('399', 'Cardinal Health');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('130', 'Thymes LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('402', 'Caleel+Hayden');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('395', 'Herbalife International of America, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('403', 'Bobbi Brown Professional Cosmetics, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('404', 'MAKEUP ART COSMETICS');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('368', 'Watkins, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('405', 'Aveda Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('406', 'The Kama Sutra');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('412', 'Schwarzkopf, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('413', 'ERBAVIVA LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('556', 'Victoria''s Secret Beauty');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('364', 'Fisk Industries Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('434', 'The Hain Celestial Group, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('416', 'Hayashi Tecnica, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('421', 'Central Solutions, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('354', 'Jemma Kidd Make Up Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('424', 'KMC Exim');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1026', 'MDSolarSciences �');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('427', 'Iredale Mineral Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('430', 'Cos.brands, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('432', 'Freeze 24/7 International, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('397', 'Reckitt Benckiser');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('448', 'Private Label Select LTD');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('449', 'Zalan Products, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('452', 'Dreambrands, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('453', 'Beilis Development');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('454', 'Trivani International, L.L.C.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('456', 'Tropical Seas, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('460', 'Framesi-North America');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('446', 'Ligi Import Corp.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('461', 'Kingman Industries, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('463', 'Benev Company, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('470', 'BABOR Cosmetics America Corp');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('464', 'University Medical Pharmaceuticals Corp');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1336', 'Revision, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('478', 'AG PROFESSIONAL HAIR CARE PRODUCTS LTD');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('481', 'L&S Cosmetics & Toiletries (M) Sdn Bhd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('483', 'Hoyu America Co.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('485', 'Olympic Mountain Products');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('450', 'CALI CHEM INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('488', 'Eng Kah Enterprise Sdn Bhd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('494', 'CCS, Clean Chemical Sweden AB');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('474', 'E.T. Browne Drug Co. Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('497', 'Dr. Babor GmbH & Co. KG');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('499', 'GERMAINE DE CAPUCCINI');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('496', 'NV Perricone LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('501', 'Goodier Cosmetics Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('475', 'Apollo Health and Beauty Care');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('852', 'Natura Bisse International');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('508', 'Sun & Skin Care Research, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('512', 'Cosswiss AG');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('505', 'Garcoa Laboratories, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('504', 'Archipelago Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('510', 'Iredale Mineral Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('522', 'Delon Laboratories (1990) Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('457', 'Pinnacle Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('515', 'DERMAQUEST, INC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('525', 'Nature''s Sunshine Products, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('526', 'MORRIS PROFUMI SPA');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('528', 'Dr. Nona International LTD');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('531', 'New Fragrance Continental Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('472', 'Allure Labs, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('534', 'Walmart');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('536', 'California Baby');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('538', 'MIRAGE COSMETICS INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('540', 'ANTONIO PUIG S.A.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('541', 'New Directions Aromatics Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('542', 'Cover FX Skin Care Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('507', 'laboratoire Sintyl SA');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('546', 'Beauty 21 Cosmetics, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('554', 'Custom Amenities Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('555', 'Smith & Vandiver Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('543', 'Biocosmatica Exel Argentina S.R.L.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('561', 'Tom''s of Maine, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('568', 'Scruples Professional Salon Products, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('575', 'CERAS ESPECIALES MARTINEZ DE SAN VICENTE SA');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('576', 'Mario Zunino & C. S.r.l.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('567', 'Zohar Cosmetics (M.F.O.) Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('577', 'Jean Philippe Fragrances Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('559', 'Smart Brands Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('579', 'Rowpar Pharmaceuticals, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('562', 'The Boots Company PLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('492', 'ITALIAN GROUP SRL');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('583', 'Pharmaceutical Specialties, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('585', 'Kenra Professional, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('558', 'Interparfums Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('586', 'Trade West, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('588', 'ProStrong Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('592', 'Bio-Derm Laboratories, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('593', 'Lise Watier Cosm�tiques Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('670', 'TRUE COSMETICS, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('587', 'B�rlind of Germany, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('590', 'Sysco Guest Supply LLC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('601', 'LCA - Laboratori di Chimica Applicata srl');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('602', 'boom creative development llc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('597', 'Advanced Aesthetics, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('603', 'Robell Research');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('609', 'AROMCA S.A');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('557', 'Smashbox Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('605', 'WORLD CLUB SUPPPLY CORP.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('720', 'IPD Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('618', 'ZACH''S WAX');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('620', 'Fragrances of Ireland Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('550', 'Neoteric Cosmetics Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('624', 'LAUREN HUTTONS GOOD STUFF LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('625', 'Beauty Treats International Co., Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('622', 'The Village Company, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('615', 'Vi-Jon, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('563', 'Selected Chemical Products Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('591', 'Skinn Cosmetics, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('570', 'Fresh, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('627', 'Continental Fragrances, Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('628', 'Ulta Salon, Cosmetics & Fragrance, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('629', 'Lumene Oy');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('560', 'Pettenon Cosmetici srl');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('584', 'Parfums de Coeur, Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('639', 'Studio Gear Cosmetics, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('640', 'Private Brand, Consumer Products, Division of McKesson');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('633', 'Concept Laboratories, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('643', 'Aubrey Organics Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('645', 'Avlon Industries, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('722', 'Exclusive Fragrances & Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('652', 'Paco Rabanne Parfums');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('654', 'Parfums Nina Ricci');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('658', 'Scherer, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('659', 'GO SMiLE, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('825', 'American Consumer Products, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('650', 'MOR Cosmetics International LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('637', 'B & C PRODUCTS, INC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('655', 'Laboratoires Dr N.G. Payot');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('667', 'Elysee Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('626', 'Lush Manufacturing Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('671', 'FRAGRANCE AND SKINCARE');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('598', 'Laboratoire Biosthetique Kosmetik GmbH & Co.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('566', 'rolland srl');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('674', 'Country Life, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('676', 'Unisource Worldwide, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('678', 'Science of Skincare, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('675', 'McKesson Medical-Surgical');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('680', 'Cypress Medical Products');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('682', 'ZEE Medical, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('685', 'Ventura International, Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('490', 'CCA Industries, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('611', 'The Sanctuary Spa Holdings Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('695', 'The Tend Skin Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('697', 'The Kroger Co.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('694', 'New Spirit Naturals, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('702', 'Blistex Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('703', 'Good ''N Natural');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('714', 'Herbal Harvest, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('711', 'Herbal Authority');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('712', 'Home Health');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('704', 'Natural Wealth');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('705', 'Nature''s Bounty');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('710', 'Vitamin World, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('715', 'PhysioLogics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('706', 'Puritan''s Pride');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('708', 'Radiance');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('709', 'Rexall-Sundown');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('666', 'Chantecaille Beaut� Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('716', 'Added Extras LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('717', 'Greenbrier International, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('418', 'Swanson Health Products');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('686', 'salerm cosm�tica profesional,Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('646', 'SOTHYS USA INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('726', 'Rapha Racing Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('728', 'PBH Marketing Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('729', 'Kaoder Industry Company, Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('731', 'Green Mountain Biotech Co., Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('733', 'Woosin Cosmetics Co., Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('274', 'Valeant Pharmaceuticals North America');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('738', 'LT White, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('740', 'Wellmade Household & Health Care Co., Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('747', 'Trish McEvoy Cosmetics Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('744', 'Ziba Beauty');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('749', 'Design Plus Health & Beauty Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('752', 'Jan Marini Skin Research, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('81', 'MSD Consumer Care, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('756', 'Montagne Jeunesse');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('757', 'Regis Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('754', 'A. P. Deauville, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('765', 'Izar Sarl');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('45', 'Parfums Loris Azzaro');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('769', 'Fusion Brands Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('779', 'Natural Solter S.L.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('773', 'I Love Cosmetics Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('781', 'Hada S.A.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('783', 'Alberto Culver');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('784', 'Soap and Glory Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('787', 'Kate Somerville Skin Care');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('798', 'Femme Couture International, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('808', 'Atlas Development Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('800', 'Kmart Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('804', 'Supervalu Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('802', 'Topco Associates, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('806', 'Rite Aid Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('811', 'The Kroger Co.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('813', 'Alessandro International GmbH');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('815', 'CAMEO TRADING CO., INC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('816', 'NEOCUTIS, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1233', 'GIB, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('819', 'Enchante Accessories, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('820', 'Champneys Henlow Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('826', 'Athena Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('827', 'Walmart');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('829', 'Prima-Derm, S.L.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('834', 'Beauty Solutions, Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('838', 'Rexall, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('713', 'Perfectly Pure');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('840', 'Pharmaceutical Specialties, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('839', 'GDCP International Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('842', 'Betco Corporation, Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('843', 'Fresh Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('844', 'American Consumer Products');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('849', 'Look Beauty Products');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('861', 'Yiwu Aris Cosmetic Manufactory');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('864', 'Nippon Menard Cosmetic Co., Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('865', 'Colorescience');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('867', 'Unite Eurotherapy');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('868', 'Core Brands');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('872', 'TAIZHOU XINZHIXUAN DAILY-USE CO.,LTD');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('876', 'Hangzhou Beja Commodity Co., Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('879', 'The BrowGal');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('880', 'Dollar Connection Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('881', 'California Mango');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('886', 'Kendo Holdings, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('889', 'Prai Beauty Group Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('887', 'Demeter Fragrance Library, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('893', 'R AND T CREATION LTD');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('894', 'RT Group');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('899', 'The Procter & Gamble Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('906', 'Test');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('908', 'Rituals Cosmetics USA, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('910', 'Zhejiang Yiwu Lucy Cosmetics Co.,Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('913', 'Ninghai Jixiang stationery Factory');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('915', 'Dongguan Changping Mei Ya Cosmetics Factory');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('920', 'Alessandro International GmbH');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('931', 'Deborah Lippmann');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('922', 'Calibre Beaut�, a division of Quadrant Cosmetics Corp.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('939', 'Laboratoires Dr N.G PAYOT');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('942', 'Novelty, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('896', 'NYX Los Angeles, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('943', 'Too Faced Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('945', 'Yantai Dupont Daily Necessities Co., Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1049', 'Japonesque');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('950', 'I Love Cosmetics Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('955', 'Amway Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1062', 'Paula''s Choice LLC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('956', 'Guthy-Renker, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('967', 'Modere, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('968', 'Space Brands Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('976', 'Crabtree & Evelyn, Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('978', 'The Mentholatum Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('984', 'Interparfums');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('985', 'High Ridge Brands');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('986', 'Express, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('997', 'Lush Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('465', 'Urban Decay Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1003', 'Alqvimia');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1005', 'Aesop USA Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1008', 'Rodan + Fields');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1009', 'Enchante Accessories, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('983', 'Hatchbeauty Products, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1012', 'Frank Body');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1011', 'Shiseido Americas Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1010', 'Kryolan Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1015', 'Upper Canada Soap & Candle Makers Corp.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1017', 'label.m USA INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1023', 'Guangzhou Zixuan Beauty Equipment Co.,Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1027', 'Hand & Nail Harmony, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1029', 'Red Carpet Manicure');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1030', 'Artistic Nail Design - Nail Alliance LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1033', 'Nail Alliance, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1035', 'Nail Alliance - Entity');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1034', 'NeoStrata Company, Inc., a Johnson & Johnson Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1000', 'MAESA LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1044', 'Perfect Angel Cosmetics & Health Co., Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1048', 'Yes To Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1046', 'Walt Disney Parks & Resorts');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1051', 'Nudestix');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1055', 'The Himalaya Drug Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1056', 'Sexy Hair Concepts');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1058', 'RMS Beauty');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1063', 'Luxury Brand Partners');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1064', 'Tweezerman International LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1028', 'APLICARE, INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1066', 'Black Up');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1069', 'eos Products, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1071', 'Soma');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1073', 'ALPHAEON Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1076', 'AMOREPACIFIC US INC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1077', 'M.T. MOCARA GmbH');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1081', 'La Prairie, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1031', 'KOS� America, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1082', 'Brodie & Stone');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1084', 'Labo International srl');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1086', 'Arcadia Beauty Labs, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1088', 'Hollywood Alliance');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1090', 'Milk Make-up');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1094', 'We are Luxe Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1096', 'Malin & Goetz');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1101', 'Reforma Group');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1103', 'Too Faced Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1102', 'FELPS USA, INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1106', 'Saje Natural Business Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1107', 'SD Biotechnologies USA, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1113', 'Imperial Dax Hair Care Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1115', 'Person & Covey');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1117', 'Fantasia Industries');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1328', 'House of Cheatham');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1125', 'Michel Design Works');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1119', 'Trader Joe''s Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1129', 'Drunk Elephant LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1128', 'Chrome Hearts LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1133', 'Cosmetic Dermatology Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1135', 'Creative Nail Design, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1136', 'Herbswork CC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1140', 'Townley Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1142', 'Centric Beauty, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1144', 'PPP&C Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1154', 'Charlotte Tilbury Beauty Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1149', 'MAVALA S.A.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1148', 'American International Industries');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1157', 'SERYSI USA INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1159', 'MILANI COSMETICS');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1160', 'Dr. Hauschka Skin Care, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1161', 'Zelens');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1163', 'Memebox Corporation');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1092', 'Vi-Jon, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1164', 'Perfect Angel Cosmetics & Health Co., Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1178', 'Apollo Health and Beauty Care Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1177', 'Spa de Soleil');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1179', 'BioTouch, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1169', 'Trademark Cosmetics, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('547', 'Ca-botana International');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1180', 'DLC Laboratories, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1183', 'FMK Labs');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1187', 'Perfect Angel Cosmetics & Health CO., Limited');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1188', 'BULGARI GLOBAL OPERATIONS SA');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1189', 'Cover FX Skincare Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1192', 'Pearlosophy USA, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1199', 'Borboleta Beauty');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1202', 'Wahl Clipper Corp.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1204', 'HUDA BEAUTY');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1207', 'HUDA BEAUTY');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1209', 'The Honest Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1210', 'Tatcha LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1196', 'PLCosmetic');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1212', 'Townley Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1214', 'OSEA Malibu');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1215', 'Fresh Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1206', 'ACQUA DI PARMA');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1217', 'Hello Body GmbH');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1213', 'Too Faced Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1218', 'ZOEVA GmbH');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1220', 'LG Household & Health Care America Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1221', 'BEST ACCESSORY GROUP');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1226', 'JINHUA B&F COSMETICS CO., LTD.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1222', '2355644 Ontario Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1228', 'ALBION COSMETICS (America), Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1231', 'MAKE UP FOR EVER');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1229', 'DBA SAS');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1239', 'Live Flickable, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1241', 'Perricone MD');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1236', 'Farmaceutici dott. Ciccarelli SpA');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1242', 'Too Faced Cosmetics');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1244', 'The Lano Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1245', 'Mirabella');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1246', 'MTG Co., Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1250', 'NINGBO MEITELI COSMETICS CO.,LTD.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1255', 'Dollar Shave Club');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1254', 'Combe Incorporated');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1256', 'eSalon.com LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1257', 'Rea.deeming Beauty, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1259', 'Yanbal USA, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1261', 'Ladove Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1262', 'MakingCosmetics Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1263', 'Carma Laboratories');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1268', 'Hayashi Worldwide');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1266', 'Bielle Cosmetics, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1273', 'Whisk Products, Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1271', 'Aloe Vera of America, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1198', 'Edgewell Personal Care Brands, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1274', 'Sunflower Distributing');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1277', 'MANA Products Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1279', 'Your Name Professional Brands');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1280', 'Taste Beauty LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1270', 'Shikai Products');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1289', 'InstaNatural LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1292', 'Pharmco Laboratories');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('12', 'USANA Health Sciences, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1248', 'MOMOTANI JUNTENKAN LTD.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1282', 'INGLOT USA LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1276', 'Duri Cosmetics Inc');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1296', 'Ningbo Rejoice I/E Co., Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1272', 'VB Cosmetics, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1301', 'Ultimate Face Cosmetics, INC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1305', 'Robanda International');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1267', 'Lornamead');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1306', 'Pfizer Consumer Healthcare');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1310', 'Market Ready');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1313', 'COLBERT+');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1316', 'Ultraceuticals Pty Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1311', 'Rainbow Cosmetics Manchester Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1317', 'G.O Holdings, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1321', 'Giovanni Cosmetics, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1309', 'PETLAB COSMETICS, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('926', 'Orly International');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1335', 'The Nature''s Bounty Company');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1338', 'H2O Plus, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1334', 'Pacha Soap Co.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1341', 'Oceana USA, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1339', 'Beach House Group');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1346', 'Oribe Hair Care LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1347', 'IT Girl Beauty, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1349', 'H&M GUTBERLET GMBH');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1332', 'Stila Style LLC.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1342', 'Herbswork CC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1352', 'SanMedica International, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1356', 'INTERPARFUMS USA, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('420', 'E. Excel, LLC');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1357', 'StriVectin Operating Company, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1358', 'Jiangxi Iris Chemical Co.,Ltd');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1377', 'DND Daisy Nail Products, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1379', 'Zschimmer & Schwarz, Inc.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1388', 'Cosmopharm Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1390', 'Guangzhou Baiyun Darong Fine Chemical Industry Co.,Ltd.');
INSERT INTO "Company" ("Company_ID", "Company_Name") VALUES ('1391', 'Turquise Global LLC');
