INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('44', 'Makeup Products (non-permanent)');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('18', 'Hair Care Products (non-coloring)');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('59', 'Nail Products');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('74', 'Personal Care Products');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('106', 'Sun-Related Products');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('6', 'Bath Products');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('90', 'Skin Care Products ');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('12', 'Fragrances');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('111', 'Tattoos and Permanent Makeup');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('32', 'Hair Coloring Products');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('68', 'Oral Hygiene Products');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('82', 'Shaving Products');
INSERT INTO "Brand" ("Category_ID", "Category_Name") VALUES ('1', 'Baby Products');
